### ISSUE TITLE
Please link clone as a fork.

### ISSUE THREAD

**Issue by glallen01** [shareef12/armymemo#1]
This repo is an unlinked clone of https://github.com/glallen01/army-memorandum-class
Please rebase the changes on a clone of the original repo to facilitate merge/pull-requests.

**Comment by shareef12** [comment]
I've rebased these changes in a forked repository. Please reference the `ctan-rebased` branch in <https://github.com/shareef12/army-memorandum-class>.

I used the upstream commit that the changes were forked from in JAN 2019 as the base commit for the rebase. I am planning on porting these changes to the latest master over the coming months, and will send pull requests as these are available.
